apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloapp-python
  labels:
    app: helloapp-python
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: helloapp-python
    spec:
      containers:
      - name: helloapp-python
        image: gcr.io/${GCLOUD_PROJECT_ID}/helloapp-python:0.1
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8000

        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 4
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 2

        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 2
          failureThreshold: 5
          successThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: helloapp-python-lb
  labels:
    app: helloapp-python
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: helloapp-python
